# doc: https://alacritty.org/config-alacritty.html

[env]
TERM = "alacritty"
LC_ALL = "en_US.UTF-8"
LANG = "en_US.UTF-8"

[shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "source /Users/xiaohei/.zshrc && tmux new -s d || tmux attach",
]

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = true
opacity = 0.9
blur = true

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 2
y = 2

[cursor.style]
blinking = "On"

[font]
size = 14
normal = { family = "Maple Mono SC NF" }

[font.bold]
family = "Maple Mono SC NF"
style = "Bold"

[keyboard]
bindings = [
  { key = "Paste", action = "Paste" },
  { key = "Copy", action = "Copy" },

  # Vi Mode
  { key = "V", mods = "Shift|Control", mode = "~Search", action = "ToggleViMode" },
  { key = "I", mode = "Vi|~Search", action = "ScrollToBottom" },
  { key = "C", mods = "Control", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "Y", mode = "Vi|~Search", action = "Copy" },
  { key = "V", mode = "Vi|~Search", action = "ToggleNormalSelection" },
  { key = "V", mods = "Shift", mode = "Vi|~Search", action = "ToggleLineSelection" },
  { key = "V", mods = "Control", mode = "Vi|~Search", action = "ToggleBlockSelection" },
  { key = "V", mods = "Alt", mode = "Vi|~Search", action = "ToggleSemanticSelection" },

  { key = "Key0", mods = "Command", action = "ResetFontSize" },
  { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
  { key = "NumpadAdd", mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
  { key = "NumpadSubtract", mods = "Command", action = "DecreaseFontSize" },

  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "C", mods = "Command", mode = "Vi|~Search", action = "ClearSelection" },

  { key = "H", mods = "Command", action = "Hide" },
  { key = "H", mods = "Command|Alt", action = "HideOtherApplications" },
  { key = "M", mods = "Command", action = "Minimize" },
  { key = "Q", mods = "Command", action = "Quit" },
  { key = "W", mods = "Command", action = "Quit" },
  { key = "F", mods = "Command|Control", action = "ToggleFullscreen" },

  # tmux
  { key = "LBracket", mods = "Command", chars = "\u0002" },
  { key = "T", mods = "Command", chars = "\u0002\u0063" },
  { key = "Tab", mods = "Control", chars = "\u0002\u000c" },
  { key = "D", mods = "Command", chars = "\u0002_" },
  { key = "D", mods = "Command|Shift", chars = "\u0002-" },
  { key = "N", mods = "Command", chars = "\u0002c" },
  { key = "Key1", mods = "Command", chars = "\u00021" },
  { key = "Key2", mods = "Command", chars = "\u00022" },
  { key = "Key3", mods = "Command", chars = "\u00023" },
]


[colors.primary]
background = '0x292C3E'
foreground = '0xEBEBEB'

[colors.cursor]
text = '0xEBEBEB'
cursor = '0xFF261E'

[colors.normal]
black = '0x0d0d0d'
red = '0xFF301B'
green = '0xA0E521'
yellow = '0xFFC620'
blue = '0x1BA6FA'
magenta = '0x8763B8'
cyan = '0x21DEEF'
white = '0xEBEBEB'

[colors.bright]
black = '0x6D7070'
red = '0xFF4352'
green = '0xB8E466'
yellow = '0xFFD750'
blue = '0x1BA6FA'
magenta = '0xA578EA'
cyan = '0x73FBF1'
white = '0xFEFEF8'
