[env]
TERM = "alacritty"
LC_ALL = "en_US.UTF-8"
LANG = "en_US.UTF-8"

[shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "source /Users/xiaohei/.zshrc && tmux new -s d || tmux attach",
]

[window]
decorations = "Buttonless"
dynamic_padding = false
dynamic_title = true
opacity = 0.9
blur = true

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 2
y = 2

[cursor.style]
blinking = "On"

[font]
size = 14
normal = { family = "Maple Mono SC NF" }

[font.bold]
family = "Maple Mono SC NF"
style = "Bold"

[keyboard]
bindings = [
  { key = "Paste", action = "Paste" },
  { key = "Copy", action = "Copy" },
  # { key = "L,         mods = Control,                    action = ClearLogNotice" },
  # { key = "L,         mods = Control, mode= ~Vi|~Search, chars = "\x0c"         " },
  # { key = "PageUp,    mods = Shift,   mode= ~Alt,        action = ScrollPageUp  " },
  # { key = "PageDown,  mods = Shift,   mode= ~Alt,        action = ScrollPageDown" },
  # { key = "Home,      mods = Shift,   mode= ~Alt,        action = ScrollToTop   " },
  # { key = "End,       mods = Shift,   mode= ~Alt,        action = ScrollToBottom" },
  # Vi Mode
  { key = "V", mods = "Shift|Control", mode = "~Search", action = "ToggleViMode" },
  # { key = "Space,  mods = Shift|Control, mode= Vi|~Search", action = "ScrollToBottom         " },
  # { key = "Escape,                      mode= Vi|~Search", action = "ClearSelection         " },
  # { key = "I,                           mode= Vi|~Search", action = "ToggleViMode           " },
  # { key = "I,                           mode= Vi|~Search", action = "ScrollToBottom         " },
  { key = "C", mods = "Control", mode = "Vi|~Search", action = "ToggleViMode" },
  # { key = "Y,      mods = Control,       mode= Vi|~Search", action = "ScrollLineUp           " },
  # { key = "E,      mods = Control,       mode= Vi|~Search", action = "ScrollLineDown         " },
  # { key = "G,                           mode= Vi|~Search", action = "ScrollToTop            " },
  # { key = "G,      mods = Shift,         mode= Vi|~Search", action = "ScrollToBottom         " },
  # { key = "B,      mods = Control,       mode= Vi|~Search", action = "ScrollPageUp           " },
  # { key = "F,      mods = Control,       mode= Vi|~Search", action = "ScrollPageDown         " },
  # { key = "U,      mods = Control,       mode= Vi|~Search", action = "ScrollHalfPageUp       " },
  # { key = "D,      mods = Control,       mode= Vi|~Search", action = "ScrollHalfPageDown     " },
  { key = "Y", mode = "Vi|~Search", action = "Copy" },
  # { key = "Y,                           mode= Vi|~Search", action = "ClearSelection         " },
  # { key = "Copy,                        mode= Vi|~Search", action = "ClearSelection         " },
  { key = "V", mode = "Vi|~Search", action = "ToggleNormalSelection" },
  { key = "V", mods = "Shift", mode = "Vi|~Search", action = "ToggleLineSelection" },
  { key = "V", mods = "Control", mode = "Vi|~Search", action = "ToggleBlockSelection" },
  { key = "V", mods = "Alt", mode = "Vi|~Search", action = "ToggleSemanticSelection" },
  # { key = "Return,                      mode= Vi|~Search", action = "Open                   " },
  # { key = "Z,                           mode= Vi|~Search", action = "CenterAroundViCursor   " },
  # { key = "K,                           mode= Vi|~Search", action = "Up                     " },
  # { key = "J,                           mode= Vi|~Search", action = "Down                   " },
  # { key = "H,                           mode= Vi|~Search", action = "Left                   " },
  # { key = "L,                           mode= Vi|~Search", action = "Right                  " },
  # { key = "Up,                          mode= Vi|~Search", action = "Up                     " },
  # { key = "Down,                        mode= Vi|~Search", action = "Down                   " },
  # { key = "Left,                        mode= Vi|~Search", action = "Left                   " },
  # { key = "Right,                       mode= Vi|~Search", action = "Right                  " },
  # { key = "Key0,                        mode= Vi|~Search", action = "First                  " },
  # { key = "Key4,   mods = Shift,         mode= Vi|~Search", action = "Last                   " },
  # { key = "Key6,   mods = Shift,         mode= Vi|~Search", action = "FirstOccupied          " },
  # { key = "H,      mods = Shift,         mode= Vi|~Search", action = "High                   " },
  # { key = "M,      mods = Shift,         mode= Vi|~Search", action = "Middle                 " },
  # { key = "L,      mods = Shift,         mode= Vi|~Search", action = "Low                    " },
  # { key = "B,                           mode= Vi|~Search", action = "SemanticLeft           " },
  # { key = "W,                           mode= Vi|~Search", action = "SemanticRight          " },
  # { key = "E,                           mode= Vi|~Search", action = "SemanticRightEnd       " },
  # { key = "B,      mods = Shift,         mode= Vi|~Search", action = "WordLeft               " },
  # { key = "W,      mods = Shift,         mode= Vi|~Search", action = "WordRight              " },
  # { key = "E,      mods = Shift,         mode= Vi|~Search", action = "WordRightEnd           " },
  # { key = "Key5,   mods = Shift,         mode= Vi|~Search", action = "Bracket                " },
  # { key = "Slash,                       mode= Vi|~Search", action = "SearchForward          " },
  # { key = "Slash,  mods = Shift,         mode= Vi|~Search", action = "SearchBackward         " },
  # { key = "N,                           mode= Vi|~Search", action = "SearchNext             " },
  # { key = "N,      mods = Shift,         mode= Vi|~Search", action = "SearchPrevious         " },
  # Search Mode
  # { key = "Return,                mode= Search|Vi,  action = SearchConfirm        " },
  # { key = "Escape,                mode= Search,     action = SearchCancel         " },
  # { key = "C,      mods = Control, mode= Search,     action = SearchCancel         " },
  # { key = "U,      mods = Control, mode= Search,     action = SearchClear          " },
  # { key = "W,      mods = Control, mode= Search,     action = SearchDeleteWord     " },
  # { key = "P,      mods = Control, mode= Search,     action = SearchHistoryPrevious" },
  # { key = "N,      mods = Control, mode= Search,     action = SearchHistoryNext    " },
  # { key = "Up,                    mode= Search,     action = SearchHistoryPrevious" },
  # { key = "Down,                  mode= Search,     action = SearchHistoryNext    " },
  # { key = "Return,                mode= Search|~Vi", action = "SearchFocusNext      " },
  # { key = "Return", mods = "Shift,   mode= Search|~Vi", action = "SearchFocusPrevious  " },
  # (Windows, Linux, and BSD only)
  # { key = "V,              mods = Control|Shift, mode= ~Vi,        action = Paste           " },
  # { key = "C,              mods = Control|Shift,                   action = Copy            " },
  # { key = "F,              mods = Control|Shift, mode= ~Search,    action = SearchForward   " },
  # { key = "B,              mods = Control|Shift, mode= ~Search,    action = SearchBackward  " },
  # { key = "C,              mods = Control|Shift, mode= Vi|~Search", action = "ClearSelection  " },
  # { key = "Insert,         mods = Shift,                           action = PasteSelection  " },
  # { key = "Key0,           mods = Control,                         action = ResetFontSize   " },
  # { key = "Equals,         mods = Control,                         action = IncreaseFontSize" },
  # { key = "Plus,           mods = Control,                         action = IncreaseFontSize" },
  # { key = "NumpadAdd,      mods = Control,                         action = IncreaseFontSize" },
  # { key = "Minus,          mods = Control,                         action = DecreaseFontSize" },
  # { key = "NumpadSubtract", mods = "Control,                         action = DecreaseFontSize" },
  # (Windows only)
  # { key = "Return,   mods = Alt,           action = ToggleFullscreen" },
  # (macOS only)
  # { key = "K,              mods = Command, mode= ~Vi|~Search, chars = "\x0c"                " },
  # { key = "K,              mods = Command, mode= ~Vi|~Search", action = "ClearHistory         " },
  # { key = "Key0,           mods = Command,                    action = ResetFontSize        " },
  # { key = "Equals,         mods = Command,                    action = IncreaseFontSize     " },
  # { key = "Plus,           mods = Command,                    action = IncreaseFontSize     " },
  # { key = "NumpadAdd,      mods = Command,                    action = IncreaseFontSize     " },
  # { key = "Minus,          mods = Command,                    action = DecreaseFontSize     " },
  # { key = "NumpadSubtract", mods = "Command,                    action = DecreaseFontSize     " },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  # { key = "C,              mods = Command, mode= Vi|~Search,  action = ClearSelection       " },
  # { key = "H,              mods = Command,                    action = Hide                 " },
  # { key = "H,              mods = Command|Alt,                action = HideOtherApplications" },
  # { key = "M,              mods = Command,                    action = Minimize             " },
  # { key = "Q,              mods = Command,                    action = Quit                 " },
  { key = "W", mods = "Command", action = "Quit" },
  # { key = "T", mods = "Command", action = "CreateNewWindow" },
  { key = "F", mods = "Command|Control", action = "ToggleFullscreen" },
  # { key = "F,              mods = Command, mode= ~Search,     action = SearchForward        " },
  # { key = "B,              mods = Command, mode= ~Search,     action = SearchBackward       " },

  # tmux
  # { key = "LBracket", mods = "Command", chars = "\x02" },
  # { key = "T", mods = "Command", chars = "\x02\x63" },
  # { key = "Tab", mods = "Control", chars = "\x02\x0c" },
  # { key = "D", mods = "Command", chars = "\x02_" },
  # { key = "D", mods = "Command|Shift", chars = "\x02-" },
  # { key = "N", mods = "Command", chars = "\x02c" },
  # { key = "Key1", mods = "Command", chars = "\x021" },
  # { key = "Key2", mods = "Command", chars = "\x022" },
  # { key = "Key3", mods = "Command", chars = "\x023" },
]


[colors.primary]
background = '0x292C3E'
foreground = '0xEBEBEB'

[colors.cursor]
text = '0xEBEBEB'
cursor = '0xFF261E'

[colors.normal]
black = '0x0d0d0d'
red = '0xFF301B'
green = '0xA0E521'
yellow = '0xFFC620'
blue = '0x1BA6FA'
magenta = '0x8763B8'
cyan = '0x21DEEF'
white = '0xEBEBEB'

[colors.bright]
black = '0x6D7070'
red = '0xFF4352'
green = '0xB8E466'
yellow = '0xFFD750'
blue = '0x1BA6FA'
magenta = '0xA578EA'
cyan = '0x73FBF1'
white = '0xFEFEF8'
