theme = "catppuccin_mocha"
[editor]
# line-number = "relative"
cursorline = true
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
# Cmd-s=":write"
# Cmd-A-l=":format"
C-s = ":w"
S-l = ":format"
